# Configuration of detekt rule sets, see https://arturbosch.github.io/detekt/comments.html.
# This file only lists the differences to the default configuration at
# https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml.

build:
  maxIssues: 0

complexity:
  ComplexMethod:
    threshold: 33
  LongMethod:
    threshold: 158
  LongParameterList:
    threshold: 8
  NestedBlockDepth:
    threshold: 10
  TooManyFunctions:
    thresholdInClasses: 19
    thresholdInObjects: 14

# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions, we need to disable
# respective rules completely.
formatting:
  ChainWrapping:
    active: false
  NoItParamInMultilineLambda:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    max: 5
  UnusedImports:
    active: true
  WildcardImport:
    excludes: ''
    excludeImports: '
      com.here.ort.analyzer.managers.*,
      com.here.ort.commands.*,
      com.here.ort.downloader.vcs.*,
      com.here.ort.gradle.*,
      com.here.ort.helper.commands.*,
      com.here.ort.reporter.reporters.*,
      com.here.ort.scanner.scanners.*,
      com.here.ort.scanner.storages.*,
      com.here.ort.spdx.SpdxLicense.*,
      com.here.ort.spdx.SpdxLicenseException.*,
      kotlinx.html.*,
      kotlinx.html.dom.*
      '
